# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 st=2 et :
VAGRANTFILE_API_VERSION = "2"
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "bento/ubuntu-20.10"
    # config.vm.box = "puppetlabs/debian-7.8-64-puppet"
    config.vm.box_check_update = false
 
    config.vm.network "private_network", ip: "172.30.1.5"
    #config.vm.network :forwarded_port, guest: 8085, host: 5005
 
    config.vm.hostname = 'envdev'

    # Provision
    #config.vm.provision :shell, :path => "install_python_git.sh"

    # Shared folder
    config.vm.synced_folder "vagrant-rsync/", "/home/rsync", create: true
end